package view;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import javafx.embed.swing.SwingNode;
@SuppressWarnings("restriction")
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Harrison
 */

public class appGUI extends Application {

	Scene scene1;
	Scene scene2;

    @Override
	public void start(Stage appStage) throws Exception {
    	appStage.setTitle("Constructor");
        initComponents(appStage);
        appStage.setScene(scene1);
        appStage.show();	
	}
    
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(Stage appStage) {
    	SwingNode bgNode = new SwingNode();
    	SwingNode loginNode = new SwingNode();
    	SwingNode textNode1 = new SwingNode();
    	SwingNode textNode2= new SwingNode();
    	SwingNode startButtonNode = new SwingNode();
        Background = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        LoginText1 = new javax.swing.JLabel();
        LoginText2 = new javax.swing.JLabel();
        StartButton = new javax.swing.JLabel();
        bgNode.setContent(Background);
        loginNode.setContent(LoginPanel);
        textNode1.setContent(LoginText1);
        textNode2.setContent(LoginText2);
        startButtonNode.setContent(StartButton);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(450, 600));

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));

        LoginText1.setBackground(new java.awt.Color(255, 255, 255));
        LoginText1.setFont(new java.awt.Font("Bahnschrift", 0, 48)); // NOI18N
        LoginText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginText1.setText("Constructor");

        LoginText2.setBackground(new java.awt.Color(255, 255, 255));
        LoginText2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        LoginText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginText2.setText("DIY Helper");

        StartButton.setBackground(new java.awt.Color(1, 75, 133));
        StartButton.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        StartButton.setForeground(new java.awt.Color(255, 255, 255));
        StartButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StartButton.setText("START");
        StartButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        StartButton.setOpaque(true);
        StartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartButtonMouseClicked(evt);
            }
        });
        VBox layout1 = new VBox(20);
        layout1.getChildren().addAll(bgNode, loginNode, textNode1, textNode2, startButtonNode);
        scene1= new Scene(layout1, 300, 250);
        appStage.setScene(scene1);
    }// </editor-fold>                        

    private void StartButtonMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        System.out.println("Start");
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	launch(args);
    }


    // Variables declaration - do not modify                     
    private javax.swing.JPanel Background;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel LoginText1;
    private javax.swing.JLabel LoginText2;
    private javax.swing.JLabel StartButton;
    // End of variables declaration     
    
    
	
}
